services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: imena
      POSTGRES_PASSWORD: imena
      POSTGRES_DB: imena
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
